package com.project.shared.engine.entities.units

object UnitRegistry {
    private val units = mapOf(
        UnitType.ALLOCATOR to UnitConfig(
            unitType = UnitType.ALLOCATOR,
            displayName = "Allocator",
            role = UnitRole.CAPTURE,
            buildTime = 0.8f,
            health = 34,
            speed = 152f,
            damage = 0,
            attackRange = 0f,
            attackCooldownMillis = 0L,
            costCpu = 2,
            costMemory = 0,
            allocatedMemory = 0,
            memoryWorkPower = 34f,
            cpuRedirectPower = 0f,
            sprite = "units/allocator.png",
            gameDescription = "Fast memory worker. Finds Memory Sources, allocates a small safe batch, then exits.",
            techDescription = "Allocation reserves usable memory for future processes. It is a short-lived operation.",
            strengths = "Very fast, no Memory cost, reliable early economy.",
            weaknesses = "No combat value, small batch, dies easily.",
            realFeature = "Allocators request memory, return usable space, then finish."
        ),

        UnitType.BUFFER to UnitConfig(
            unitType = UnitType.BUFFER,
            displayName = "Buffer",
            role = UnitRole.CAPTURE,
            buildTime = 1.2f,
            health = 52,
            speed = 118f,
            damage = 0,
            attackRange = 0f,
            attackCooldownMillis = 0L,
            costCpu = 3,
            costMemory = 0,
            allocatedMemory = 0,
            memoryWorkPower = 46f,
            cpuRedirectPower = 0f,
            sprite = "units/buffer.png",
            gameDescription = "Allocates a larger temporary Memory batch, but works slower than Allocator.",
            techDescription = "A buffer stores data in transit. It improves throughput, but oversized buffers can hide pressure.",
            strengths = "Larger Memory batch, more durable than Allocator.",
            weaknesses = "Slower, higher CPU cost, still cannot fight.",
            realFeature = "Buffers smooth bursts, but they are temporary storage and must be sized carefully."
        ),

        UnitType.MEMORY_POOL to UnitConfig(
            unitType = UnitType.MEMORY_POOL,
            displayName = "Memory Pool",
            role = UnitRole.CAPTURE,
            buildTime = 2.0f,
            health = 84,
            speed = 62f,
            damage = 0,
            attackRange = 0f,
            attackCooldownMillis = 0L,
            costCpu = 5,
            costMemory = 0,
            allocatedMemory = 0,
            memoryWorkPower = 62f,
            cpuRedirectPower = 0f,
            sprite = "units/memory_pool.png",
            gameDescription = "Slow heavy memory worker. Allocates a large batch and then exits.",
            techDescription = "A memory pool preallocates chunks to reduce future allocation overhead.",
            strengths = "Largest Memory batch, harder to kill.",
            weaknesses = "Slow to reach source, expensive CPU, vulnerable to interruption.",
            realFeature = "Pools trade upfront cost for faster repeated allocations later."
        ),

        UnitType.DMA_CONTROLLER to UnitConfig(
            unitType = UnitType.DMA_CONTROLLER,
            displayName = "DMA Controller",
            role = UnitRole.CAPTURE,
            buildTime = 1.7f,
            health = 64,
            speed = 96f,
            damage = 0,
            attackRange = 0f,
            attackCooldownMillis = 0L,
            costCpu = 4,
            costMemory = 0,
            allocatedMemory = 0,
            memoryWorkPower = 40f,
            cpuRedirectPower = 0.6f,
            sprite = "units/dma_controller.png",
            gameDescription = "Hybrid resource unit. Allocates Memory and can redirect a small CPU share.",
            techDescription = "DMA moves data without fully occupying the CPU, improving data transfer efficiency.",
            strengths = "Flexible economy tool.",
            weaknesses = "Not best at Memory or CPU, fragile.",
            realFeature = "Direct Memory Access offloads data movement from the CPU."
        ),

        UnitType.CPU_SCHEDULER to UnitConfig(
            unitType = UnitType.CPU_SCHEDULER,
            displayName = "CPU Scheduler",
            role = UnitRole.CAPTURE,
            buildTime = 1.3f,
            health = 50,
            speed = 124f,
            damage = 0,
            attackRange = 0f,
            attackCooldownMillis = 0L,
            costCpu = 2,
            costMemory = 4,
            allocatedMemory = 4,
            memoryWorkPower = 0f,
            cpuRedirectPower = 1.4f,
            sprite = "units/cpu_scheduler.png",
            gameDescription = "Redirects CPU share from CPU nodes toward your system.",
            techDescription = "A scheduler decides which work gets CPU time.",
            strengths = "Efficient CPU capture, cheap, fast.",
            weaknesses = "No combat, low HP, needs CPU node presence.",
            realFeature = "Scheduling is proportional allocation of compute time between runnable tasks."
        ),

        UnitType.LOAD_BALANCER to UnitConfig(
            unitType = UnitType.LOAD_BALANCER,
            displayName = "Load Balancer",
            role = UnitRole.CAPTURE,
            buildTime = 2.2f,
            health = 92,
            speed = 74f,
            damage = 0,
            attackRange = 0f,
            attackCooldownMillis = 0L,
            costCpu = 5,
            costMemory = 8,
            allocatedMemory = 8,
            memoryWorkPower = 0f,
            cpuRedirectPower = 2.2f,
            sprite = "units/load_balancer.png",
            gameDescription = "Strong CPU redirector. Best when protected near contested CPU nodes.",
            techDescription = "Load balancing distributes work across capacity so no worker is overloaded.",
            strengths = "High CPU share, durable.",
            weaknesses = "Slow, expensive, useless away from CPU nodes.",
            realFeature = "Balancers improve throughput by distributing work proportionally."
        ),

        UnitType.INTERRUPT_HANDLER to UnitConfig(
            unitType = UnitType.INTERRUPT_HANDLER,
            displayName = "Interrupt Handler",
            role = UnitRole.CAPTURE,
            buildTime = 1.0f,
            health = 38,
            speed = 156f,
            damage = 0,
            attackRange = 0f,
            attackCooldownMillis = 0L,
            costCpu = 3,
            costMemory = 3,
            allocatedMemory = 3,
            memoryWorkPower = 0f,
            cpuRedirectPower = 1.0f,
            sprite = "units/interrupt_handler.png",
            gameDescription = "Fast CPU responder. Quickly contests CPU nodes but is fragile.",
            techDescription = "Interrupt handlers respond to urgent hardware/software events before normal flow continues.",
            strengths = "Fastest CPU contest unit.",
            weaknesses = "Very fragile, low sustained redirect power.",
            realFeature = "Interrupts are quick reactions, not long-running workers."
        ),

        UnitType.GARBAGE_COLLECTOR to UnitConfig(
            unitType = UnitType.GARBAGE_COLLECTOR,
            displayName = "Garbage Collector",
            role = UnitRole.SUPPORT,
            buildTime = 1.6f,
            health = 58,
            speed = 88f,
            damage = 0,
            attackRange = 0f,
            attackCooldownMillis = 0L,
            costCpu = 7,
            costMemory = 0,
            allocatedMemory = 0,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/garbage_collector.png",
            gameDescription = "Finds dead allied units, frees their allocated Memory, removes them from the map, then exits.",
            techDescription = "GC does not create memory and does not heal live objects. It reclaims unreachable/dead allocations.",
            strengths = "Costs no Memory, recovers Memory from dead allied processes.",
            weaknesses = "High CPU cost, cannot fight, can be killed while sweeping.",
            realFeature = "Garbage collection is reachability cleanup: dead/unreachable objects are swept so memory can be reused."
        ),

        UnitType.THREAD_GUARD to UnitConfig(
            unitType = UnitType.THREAD_GUARD,
            displayName = "Thread Guard",
            role = UnitRole.DEFENSE,
            buildTime = 3.0f,
            health = 135,
            speed = 68f,
            damage = 14,
            attackRange = 70f,
            attackCooldownMillis = 950L,
            costCpu = 6,
            costMemory = 10,
            allocatedMemory = 10,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/thread_guard.png",
            gameDescription = "Durable defender that guards a local area around its rally point.",
            techDescription = "A guarded thread protects critical sections and shared resources from unsafe access.",
            strengths = "High HP, good at holding nodes and factory approaches.",
            weaknesses = "Slow, poor at chasing, weak at attacking structures.",
            realFeature = "Synchronization improves safety, but excessive locking reduces mobility and throughput."
        ),

        UnitType.INJECTOR to UnitConfig(
            unitType = UnitType.INJECTOR,
            displayName = "Injector",
            role = UnitRole.ATTACK,
            buildTime = 2.2f,
            health = 78,
            speed = 112f,
            damage = 26,
            attackRange = 64f,
            attackCooldownMillis = 780L,
            costCpu = 7,
            costMemory = 11,
            allocatedMemory = 11,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/injector.png",
            gameDescription = "Aggressive process that prioritizes factories and the enemy Core.",
            techDescription = "Injection is powerful because it changes important execution paths directly, but it is risky without protection.",
            strengths = "High structure pressure, fast kill threat.",
            weaknesses = "Fragile if focused by defenders.",
            realFeature = "Dependency/code injection can be productive or dangerous depending on validation and boundaries."
        ),

        UnitType.DEADLOCK to UnitConfig(
            unitType = UnitType.DEADLOCK,
            displayName = "Deadlock",
            role = UnitRole.SPELL,
            buildTime = 0.2f,
            health = 1,
            speed = 0f,
            damage = 0,
            attackRange = 145f,
            attackCooldownMillis = 0L,
            costCpu = 8,
            costMemory = 0,
            allocatedMemory = 0,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/deadlock.png",
            gameDescription = "Area control spell that temporarily stops enemy processes.",
            techDescription = "A deadlock blocks progress because processes wait on each other forever.",
            strengths = "Can flip fights and stop dangerous pushes.",
            weaknesses = "Expensive CPU cooldown, no direct damage.",
            realFeature = "Deadlocks are not slowdowns; they are progress failures caused by circular waiting."
        ),

        UnitType.OVERCLOCK to UnitConfig(
            unitType = UnitType.OVERCLOCK,
            displayName = "Overclock",
            role = UnitRole.SPELL,
            buildTime = 0.2f,
            health = 1,
            speed = 0f,
            damage = 0,
            attackRange = 150f,
            attackCooldownMillis = 0L,
            costCpu = 7,
            costMemory = 0,
            allocatedMemory = 0,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/overclock.png",
            gameDescription = "Temporary throughput boost for allied processes in an area.",
            techDescription = "Overclocking increases throughput for a limited time, but consumes compute headroom.",
            strengths = "Great for timing attacks and faster GC/Allocator operations.",
            weaknesses = "Does nothing without active allied processes.",
            realFeature = "Performance boosts are situational and bounded by stability and resource limits."
        ),

        UnitType.CACHE_RUNNER to UnitConfig(
            unitType = UnitType.CACHE_RUNNER,
            displayName = "Cache Runner",
            role = UnitRole.CAPTURE,
            buildTime = 1.0f,
            health = 28,
            speed = 182f,
            damage = 5,
            attackRange = 48f,
            attackCooldownMillis = 720L,
            costCpu = 3,
            costMemory = 4,
            allocatedMemory = 4,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0.8f,
            sprite = "units/cache_runner.png",
            gameDescription = "Fast scout/capturer that lightly redirects CPU and harasses weak processes.",
            techDescription = "Cache locality gives speed, but cached state is small and fragile.",
            strengths = "Very fast tempo and early CPU contest.",
            weaknesses = "Low HP and weak sustained CPU share.",
            realFeature = "Caches improve access speed, but invalidation and small capacity make them fragile."
        ),

        UnitType.FIREWALL to UnitConfig(
            unitType = UnitType.FIREWALL,
            displayName = "Firewall",
            role = UnitRole.DEFENSE,
            buildTime = 3.4f,
            health = 165,
            speed = 48f,
            damage = 11,
            attackRange = 82f,
            attackCooldownMillis = 1050L,
            costCpu = 8,
            costMemory = 14,
            allocatedMemory = 14,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/firewall.png",
            gameDescription = "Slow defensive boundary that holds a narrow approach.",
            techDescription = "A firewall filters hostile traffic before it reaches critical system parts.",
            strengths = "Excellent static defense and Core protection.",
            weaknesses = "Slow, expensive, poor map pressure.",
            realFeature = "Security boundaries are strongest when positioned before critical resources."
        ),

        UnitType.COROUTINE_ARCHER to UnitConfig(
            unitType = UnitType.COROUTINE_ARCHER,
            displayName = "Coroutine Archer",
            role = UnitRole.ATTACK,
            buildTime = 2.8f,
            health = 52,
            speed = 104f,
            damage = 18,
            attackRange = 165f,
            attackCooldownMillis = 920L,
            costCpu = 7,
            costMemory = 10,
            allocatedMemory = 10,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/coroutine_archer.png",
            gameDescription = "Long-range attacker that performs work from a safe distance.",
            techDescription = "Coroutines represent asynchronous work that can continue without blocking the whole system.",
            strengths = "Long range and safe damage.",
            weaknesses = "Fragile, needs guards.",
            realFeature = "Async tasks are efficient, but require scheduling and lifecycle control."
        ),

        UnitType.PATCH_HEALER to UnitConfig(
            unitType = UnitType.PATCH_HEALER,
            displayName = "Patch Healer",
            role = UnitRole.SUPPORT,
            buildTime = 2.4f,
            health = 58,
            speed = 98f,
            damage = 2,
            attackRange = 112f,
            attackCooldownMillis = 1250L,
            costCpu = 4,
            costMemory = 7,
            allocatedMemory = 7,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/patch_healer.png",
            gameDescription = "Repairs living allied processes and helps a push survive.",
            techDescription = "A patch fixes live system behavior; unlike GC, it does not reclaim dead allocations.",
            strengths = "Cheap sustain for living units.",
            weaknesses = "Fragile, no memory recovery.",
            realFeature = "Patching stabilizes live services; it is maintenance, not garbage collection."
        ),

        UnitType.STACK_FRAME to UnitConfig(
            unitType = UnitType.STACK_FRAME,
            displayName = "Stack Frame",
            role = UnitRole.ATTACK,
            buildTime = 0.9f,
            health = 38,
            speed = 140f,
            damage = 22,
            attackRange = 54f,
            attackCooldownMillis = 600L,
            costCpu = 3,
            costMemory = 2,
            allocatedMemory = 2,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/stack_frame.png",
            gameDescription = "Short-lived burst attacker. Executes one quick strike, then returns from the call.",
            techDescription = "A stack frame stores local data for one function call and disappears after return.",
            strengths = "Cheap, fast, good for burst trades.",
            weaknesses = "Does not persist; poor long fights.",
            realFeature = "Stack allocation is fast and scoped to function execution."
        ),

        UnitType.HEAP_BLOCK to UnitConfig(
            unitType = UnitType.HEAP_BLOCK,
            displayName = "Heap Block",
            role = UnitRole.DEFENSE,
            buildTime = 1.8f,
            health = 115,
            speed = 36f,
            damage = 4,
            attackRange = 45f,
            attackCooldownMillis = 1400L,
            costCpu = 2,
            costMemory = 12,
            allocatedMemory = 12,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/heap_block.png",
            gameDescription = "Bulky memory-heavy blocker. Good wall, bad tempo.",
            techDescription = "Heap objects live beyond a single call and must be managed or collected.",
            strengths = "High HP for CPU cost; creates a body on the map.",
            weaknesses = "Consumes much Memory and becomes leak material when dead.",
            realFeature = "Heap allocation is flexible but needs lifecycle management."
        ),

        UnitType.POINTER to UnitConfig(
            unitType = UnitType.POINTER,
            displayName = "Pointer",
            role = UnitRole.SUPPORT,
            buildTime = 1.2f,
            health = 44,
            speed = 126f,
            damage = 1,
            attackRange = 150f,
            attackCooldownMillis = 1000L,
            costCpu = 4,
            costMemory = 3,
            allocatedMemory = 3,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/pointer.png",
            gameDescription = "Marks enemy targets so allied attacks deal more damage to the referenced object.",
            techDescription = "A pointer references an object; the reference itself is lightweight but changes how code accesses data.",
            strengths = "Amplifies focus fire.",
            weaknesses = "Weak alone and fragile.",
            realFeature = "References are powerful because many operations can point to the same object."
        ),

        UnitType.NULL_POINTER to UnitConfig(
            unitType = UnitType.NULL_POINTER,
            displayName = "Null Pointer",
            role = UnitRole.SPELL,
            buildTime = 0.1f,
            health = 1,
            speed = 0f,
            damage = 34,
            attackRange = 150f,
            attackCooldownMillis = 0L,
            costCpu = 7,
            costMemory = 0,
            allocatedMemory = 0,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/null_pointer.png",
            gameDescription = "Single-target crash spell. Damages and briefly stuns the nearest enemy process.",
            techDescription = "Null pointer access crashes execution because code dereferences nothing.",
            strengths = "Great pick-off tool.",
            weaknesses = "Single target, requires timing.",
            realFeature = "Null references are not empty objects; they are invalid references."
        ),

        UnitType.EXCEPTION_HANDLER to UnitConfig(
            unitType = UnitType.EXCEPTION_HANDLER,
            displayName = "Exception Handler",
            role = UnitRole.SUPPORT,
            buildTime = 2.0f,
            health = 64,
            speed = 88f,
            damage = 2,
            attackRange = 120f,
            attackCooldownMillis = 1200L,
            costCpu = 5,
            costMemory = 8,
            allocatedMemory = 8,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/exception_handler.png",
            gameDescription = "Protects nearby allies from one fatal crash by catching the exception.",
            techDescription = "Exception handling prevents local failure from terminating the whole flow.",
            strengths = "Can save an important unit once.",
            weaknesses = "Limited shield and weak combat.",
            realFeature = "Handled exceptions preserve control flow; unhandled exceptions crash the process."
        ),

        UnitType.LOOP to UnitConfig(
            unitType = UnitType.LOOP,
            displayName = "Loop",
            role = UnitRole.ATTACK,
            buildTime = 1.8f,
            health = 72,
            speed = 84f,
            damage = 7,
            attackRange = 72f,
            attackCooldownMillis = 520L,
            costCpu = 5,
            costMemory = 7,
            allocatedMemory = 7,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/loop.png",
            gameDescription = "Repeats a small attack very often. Efficient against low armor targets.",
            techDescription = "Loops repeat instructions until a condition changes.",
            strengths = "Consistent repeated pressure.",
            weaknesses = "Low burst and vulnerable to area control.",
            realFeature = "Loops are simple and powerful, but bad termination conditions create runaway work."
        ),

        UnitType.RECURSIVE_CALL to UnitConfig(
            unitType = UnitType.RECURSIVE_CALL,
            displayName = "Recursive Call",
            role = UnitRole.ATTACK,
            buildTime = 2.5f,
            health = 68,
            speed = 78f,
            damage = 12,
            attackRange = 82f,
            attackCooldownMillis = 900L,
            costCpu = 6,
            costMemory = 9,
            allocatedMemory = 9,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/recursive_call.png",
            gameDescription = "Grows stronger every few seconds, but eventually risks stack overflow damage to itself.",
            techDescription = "Recursion solves nested problems elegantly, but each call consumes stack depth.",
            strengths = "Scales if protected.",
            weaknesses = "Can damage itself after too much depth.",
            realFeature = "Recursive algorithms need a base case and depth awareness."
        ),

        UnitType.MUTEX to UnitConfig(
            unitType = UnitType.MUTEX,
            displayName = "Mutex",
            role = UnitRole.DEFENSE,
            buildTime = 2.6f,
            health = 118,
            speed = 54f,
            damage = 8,
            attackRange = 72f,
            attackCooldownMillis = 980L,
            costCpu = 6,
            costMemory = 9,
            allocatedMemory = 9,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/mutex.png",
            gameDescription = "Protects nearby allied processes by reducing incoming damage.",
            techDescription = "A mutex allows one thread at a time into a critical section.",
            strengths = "Damage mitigation aura.",
            weaknesses = "Slow and can contribute to deadlock risk if misused.",
            realFeature = "Mutual exclusion improves correctness but can reduce concurrency."
        ),

        UnitType.SEMAPHORE to UnitConfig(
            unitType = UnitType.SEMAPHORE,
            displayName = "Semaphore",
            role = UnitRole.SUPPORT,
            buildTime = 2.4f,
            health = 76,
            speed = 76f,
            damage = 3,
            attackRange = 90f,
            attackCooldownMillis = 1100L,
            costCpu = 6,
            costMemory = 8,
            allocatedMemory = 8,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/semaphore.png",
            gameDescription = "Boosts throughput of nearby allied processes by allowing limited parallel access.",
            techDescription = "A semaphore controls how many workers may use a resource at the same time.",
            strengths = "Local speed/attack tempo aura.",
            weaknesses = "Weak alone, needs a group.",
            realFeature = "Semaphores coordinate limited parallelism rather than exclusive access."
        ),

        UnitType.OBSERVER to UnitConfig(
            unitType = UnitType.OBSERVER,
            displayName = "Observer",
            role = UnitRole.SUPPORT,
            buildTime = 1.7f,
            health = 48,
            speed = 112f,
            damage = 1,
            attackRange = 170f,
            attackCooldownMillis = 1400L,
            costCpu = 4,
            costMemory = 5,
            allocatedMemory = 5,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/observer.png",
            gameDescription = "Marks enemies from range, making them more vulnerable.",
            techDescription = "Observer pattern lets objects react to changes without tight coupling.",
            strengths = "Improves team focus and target visibility.",
            weaknesses = "Fragile and low direct damage.",
            realFeature = "Observers decouple notification from action, but uncontrolled listeners can leak memory."
        )
    )

    val defaultDeck: List<UnitType> = listOf(
        UnitType.ALLOCATOR,
        UnitType.CPU_SCHEDULER,
        UnitType.GARBAGE_COLLECTOR,
        UnitType.THREAD_GUARD,
        UnitType.INJECTOR,
        UnitType.DEADLOCK
    )

    fun getConfig(type: UnitType): UnitConfig {
        return units[type] ?: error("No UnitConfig registered for $type")
    }

    fun all(): List<UnitConfig> {
        return units.values.toList()
    }
}
