package com.project.shared.engine.entities.units

object UnitRegistry {
    private val units = mapOf(
        UnitType.ALLOCATOR to UnitConfig(
            unitType = UnitType.ALLOCATOR,
            displayName = "Allocator",
            role = UnitRole.CAPTURE,
            buildTime = 0.8f,
            health = 34,
            speed = 152f,
            damage = 0,
            attackRange = 0f,
            attackCooldownMillis = 0L,
            costCpu = 2,
            costMemory = 0,
            allocatedMemory = 0,
            memoryWorkPower = 34f,
            cpuRedirectPower = 0f,
            sprite = "units/allocator.png",
            gameDescription = "Быстрый работник памяти. Находит источники Memory, выделяет небольшой безопасный блок и уходит.",
            techDescription = "Выделение резервирует память для будущих процессов. Операция короткая по времени.",
            strengths = "Очень быстрый, не требует Memory, надёжен на ранней стадии экономики.",
            weaknesses = "Не участвует в бою, малый объём выделяемой памяти, уязвим.",
            realFeature = "Allocator запрашивает память, возвращает пригодный для использования кусок и завершается."
        ),

        UnitType.BUFFER to UnitConfig(
            unitType = UnitType.BUFFER,
            displayName = "Buffer",
            role = UnitRole.CAPTURE,
            buildTime = 1.2f,
            health = 52,
            speed = 118f,
            damage = 0,
            attackRange = 0f,
            attackCooldownMillis = 0L,
            costCpu = 3,
            costMemory = 0,
            allocatedMemory = 0,
            memoryWorkPower = 46f,
            cpuRedirectPower = 0f,
            sprite = "units/buffer.png",
            gameDescription = "Выделяет более крупную временную пачку Memory, но работает медленнее, чем Allocator.",
            techDescription = "Буфер хранит данные в транзите. Увеличивает пропускную способность, но слишком большие буферы скрывают нагрузку.",
            strengths = "Более крупная пачка Memory, живучее, чем Allocator.",
            weaknesses = "Медленнее, выше стоимость CPU, по-прежнему не боевая единица.",
            realFeature = "Буферы сглаживают всплески, но являются временным хранилищем и требуют правильного размера."
        ),

        UnitType.MEMORY_POOL to UnitConfig(
            unitType = UnitType.MEMORY_POOL,
            displayName = "Memory Pool",
            role = UnitRole.CAPTURE,
            buildTime = 2.0f,
            health = 84,
            speed = 62f,
            damage = 0,
            attackRange = 0f,
            attackCooldownMillis = 0L,
            costCpu = 5,
            costMemory = 0,
            allocatedMemory = 0,
            memoryWorkPower = 62f,
            cpuRedirectPower = 0f,
            sprite = "units/memory_pool.png",
            gameDescription = "Медленный крупный работник памяти. Выделяет большую пачку и затем уходит.",
            techDescription = "Memory Pool предварительно выделяет чанки, чтобы снизить накладные расходы при последующих выделениях.",
            strengths = "Наибольшая пачка Memory, труднее уничтожить.",
            weaknesses = "Медленно добирается до источника, дорогой по CPU, уязвим к прерыванию.",
            realFeature = "Pools платят заранее, чтобы ускорить повторные выделения позже."
        ),

        UnitType.DMA_CONTROLLER to UnitConfig(
            unitType = UnitType.DMA_CONTROLLER,
            displayName = "DMA Controller",
            role = UnitRole.CAPTURE,
            buildTime = 1.7f,
            health = 64,
            speed = 96f,
            damage = 0,
            attackRange = 0f,
            attackCooldownMillis = 0L,
            costCpu = 4,
            costMemory = 0,
            allocatedMemory = 0,
            memoryWorkPower = 40f,
            cpuRedirectPower = 0.6f,
            sprite = "units/dma_controller.png",
            gameDescription = "Гибридный ресурсный юнит. Выделяет Memory и может перенаправлять небольшую долю CPU.",
            techDescription = "DMA перемещает данные без полного занятия CPU, повышая эффективность передачи.",
            strengths = "Гибкий инструмент экономики.",
            weaknesses = "Не лучший ни в Memory, ни в CPU, хрупок.",
            realFeature = "Direct Memory Access разгружает CPU при перемещении данных."
        ),

        UnitType.CPU_SCHEDULER to UnitConfig(
            unitType = UnitType.CPU_SCHEDULER,
            displayName = "CPU Scheduler",
            role = UnitRole.CAPTURE,
            buildTime = 1.3f,
            health = 50,
            speed = 124f,
            damage = 0,
            attackRange = 0f,
            attackCooldownMillis = 0L,
            costCpu = 2,
            costMemory = 4,
            allocatedMemory = 4,
            memoryWorkPower = 0f,
            cpuRedirectPower = 1.4f,
            sprite = "units/cpu_scheduler.png",
            gameDescription = "Перенаправляет долю CPU с CPU-узлов в сторону вашей системы.",
            techDescription = "Scheduler решает, какая работа получает CPU-время.",
            strengths = "Эффективный захват CPU, дешёвый, быстрый.",
            weaknesses = "Не боевой, низкое HP, требует присутствия CPU-узла.",
            realFeature = "Планирование пропорционально распределяет вычислительное время между задачами."
        ),

        UnitType.LOAD_BALANCER to UnitConfig(
            unitType = UnitType.LOAD_BALANCER,
            displayName = "Load Balancer",
            role = UnitRole.CAPTURE,
            buildTime = 2.2f,
            health = 92,
            speed = 74f,
            damage = 0,
            attackRange = 0f,
            attackCooldownMillis = 0L,
            costCpu = 5,
            costMemory = 8,
            allocatedMemory = 8,
            memoryWorkPower = 0f,
            cpuRedirectPower = 2.2f,
            sprite = "units/load_balancer.png",
            gameDescription = "Сильный перенаправитель CPU. Лучший при защите возле спорных CPU-узлов.",
            techDescription = "Load balancer распределяет работу по мощностям, чтобы избежать перегрузки отдельных исполнителей.",
            strengths = "Большая доля CPU, вынослив.",
            weaknesses = "Медленный, дорогой, бесполезен вдали от CPU-узлов.",
            realFeature = "Балансировщики повышают пропускную способность через пропорциональное распределение работы."
        ),

        UnitType.INTERRUPT_HANDLER to UnitConfig(
            unitType = UnitType.INTERRUPT_HANDLER,
            displayName = "Interrupt Handler",
            role = UnitRole.CAPTURE,
            buildTime = 1.0f,
            health = 38,
            speed = 156f,
            damage = 0,
            attackRange = 0f,
            attackCooldownMillis = 0L,
            costCpu = 3,
            costMemory = 3,
            allocatedMemory = 3,
            memoryWorkPower = 0f,
            cpuRedirectPower = 1.0f,
            sprite = "units/interrupt_handler.png",
            gameDescription = "Быстрый ответчик CPU. Быстро оспаривает CPU-узлы, но хрупок.",
            techDescription = "Interrupt handler реагирует на срочные аппаратные/программные события прежде, чем продолжится обычный поток.",
            strengths = "Самый быстрый юнит для захвата CPU.",
            weaknesses = "Очень хрупок, малая постоянная сила перенаправления.",
            realFeature = "Прерывания — быстрые реакции, а не долгоживущие работники."
        ),

        UnitType.GARBAGE_COLLECTOR to UnitConfig(
            unitType = UnitType.GARBAGE_COLLECTOR,
            displayName = "Garbage Collector",
            role = UnitRole.SUPPORT,
            buildTime = 1.6f,
            health = 58,
            speed = 88f,
            damage = 0,
            attackRange = 0f,
            attackCooldownMillis = 0L,
            costCpu = 7,
            costMemory = 0,
            allocatedMemory = 0,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/garbage_collector.png",
            gameDescription = "Находит мёртвые союзные юниты, освобождает выделенную ими Memory, удаляет их с карты и уходит.",
            techDescription = "GC не создаёт Memory и не лечит живые объекты. Он возвращает недостижимые/мёртвые выделения.",
            strengths = "Не требует Memory, возвращает Memory от мёртвых союзников.",
            weaknesses = "Большая стоимость CPU, не боевая, может быть уничтожен во время обхода.",
            realFeature = "Сборка мусора — это очистка достижимости: мёртвые объекты удаляются, чтобы память могла быть повторно использована."
        ),

        UnitType.THREAD_GUARD to UnitConfig(
            unitType = UnitType.THREAD_GUARD,
            displayName = "Thread Guard",
            role = UnitRole.DEFENSE,
            buildTime = 3.0f,
            health = 135,
            speed = 68f,
            damage = 14,
            attackRange = 70f,
            attackCooldownMillis = 950L,
            costCpu = 6,
            costMemory = 10,
            allocatedMemory = 10,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/thread_guard.png",
            gameDescription = "Выносливый защитник, охраняющий локальную область вокруг точки сбора.",
            techDescription = "Защищённый поток охраняет критические секции и общие ресурсы от небезопасного доступа.",
            strengths = "Высокое HP, хорош в удержании узлов и подходов к фабрикам.",
            weaknesses = "Медленный, плохо преследует, слаб против структур.",
            realFeature = "Синхронизация повышает безопасность, но чрезмерная блокировка снижает подвижность и пропускную способность."
        ),

        UnitType.INJECTOR to UnitConfig(
            unitType = UnitType.INJECTOR,
            displayName = "Injector",
            role = UnitRole.ATTACK,
            buildTime = 2.2f,
            health = 78,
            speed = 112f,
            damage = 26,
            attackRange = 64f,
            attackCooldownMillis = 780L,
            costCpu = 7,
            costMemory = 11,
            allocatedMemory = 11,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/injector.png",
            gameDescription = "Агрессивный процесс, который приоритетно атакует фабрики и ядро противника.",
            techDescription = "Инъекция мощна, так как изменяет важные пути выполнения напрямую, но опасна без защиты.",
            strengths = "Сильное давление на структуры, быстрое устранение целей.",
            weaknesses = "Хрупок при фокусе со стороны защитников.",
            realFeature = "Внедрение зависимостей/кода может быть полезным или опасным в зависимости от проверки и границ."
        ),

        UnitType.DEADLOCK to UnitConfig(
            unitType = UnitType.DEADLOCK,
            displayName = "Deadlock",
            role = UnitRole.SPELL,
            buildTime = 0.2f,
            health = 1,
            speed = 0f,
            damage = 0,
            attackRange = 145f,
            attackCooldownMillis = 0L,
            costCpu = 8,
            costMemory = 0,
            allocatedMemory = 0,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/deadlock.png",
            gameDescription = "Спелл контроля области, временно останавливающий вражеские процессы.",
            techDescription = "Deadlock блокирует прогресс, потому что процессы бесконечно ждут друг друга.",
            strengths = "Может перевернуть сражение и остановить опасные атаки.",
            weaknesses = "Дорогой по CPU и имеет кулдаун, не наносит прямого урона.",
            realFeature = "Deadlock — это не замедление, а ошибка прогресса, вызванная круговым ожиданием."
        ),

        UnitType.OVERCLOCK to UnitConfig(
            unitType = UnitType.OVERCLOCK,
            displayName = "Overclock",
            role = UnitRole.SPELL,
            buildTime = 0.2f,
            health = 1,
            speed = 0f,
            damage = 0,
            attackRange = 150f,
            attackCooldownMillis = 0L,
            costCpu = 7,
            costMemory = 0,
            allocatedMemory = 0,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/overclock.png",
            gameDescription = "Временное повышение пропускной способности союзных процессов в области.",
            techDescription = "Overclock увеличивает пропускную способность на ограниченное время, но потребляет вычислительные ресурсы.",
            strengths = "Хорош для синхронных атак и ускорения GC/Allocator операций.",
            weaknesses = "Бессмыслен, если рядом нет активных союзных процессов.",
            realFeature = "Улучшение производительности ситуативно и ограничено стабильностью и ресурсами."
        ),

        UnitType.CACHE_RUNNER to UnitConfig(
            unitType = UnitType.CACHE_RUNNER,
            displayName = "Cache Runner",
            role = UnitRole.CAPTURE,
            buildTime = 1.0f,
            health = 28,
            speed = 182f,
            damage = 5,
            attackRange = 48f,
            attackCooldownMillis = 720L,
            costCpu = 3,
            costMemory = 4,
            allocatedMemory = 4,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0.8f,
            sprite = "units/cache_runner.png",
            gameDescription = "Быстрый разведчик/захватчик, слегка перенаправляет CPU и докучает слабым процессам.",
            techDescription = "Локальность кэша даёт скорость, но кэшированное состояние мало и хрупко.",
            strengths = "Очень быстрый темп и ранняя конкуренция за CPU.",
            weaknesses = "Низкое HP и малая устойчивость перенаправления CPU.",
            realFeature = "Кэши улучшают скорость доступа, но инвалидация и малый объём делают их хрупкими."
        ),

        UnitType.FIREWALL to UnitConfig(
            unitType = UnitType.FIREWALL,
            displayName = "Firewall",
            role = UnitRole.DEFENSE,
            buildTime = 3.4f,
            health = 165,
            speed = 48f,
            damage = 11,
            attackRange = 82f,
            attackCooldownMillis = 1050L,
            costCpu = 8,
            costMemory = 14,
            allocatedMemory = 14,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/firewall.png",
            gameDescription = "Медленная защитная граница, которая удерживает узкий подход.",
            techDescription = "Firewall фильтрует враждебный трафик прежде, чем он достигнет критических частей системы.",
            strengths = "Отличная статическая защита и защита Ядра.",
            weaknesses = "Медленная, дорогая, слабое давление на карте.",
            realFeature = "Позиционные границы безопасности наиболее эффективны перед критическими ресурсами."
        ),

        UnitType.COROUTINE_ARCHER to UnitConfig(
            unitType = UnitType.COROUTINE_ARCHER,
            displayName = "Coroutine Archer",
            role = UnitRole.ATTACK,
            buildTime = 2.8f,
            health = 52,
            speed = 104f,
            damage = 18,
            attackRange = 165f,
            attackCooldownMillis = 920L,
            costCpu = 7,
            costMemory = 10,
            allocatedMemory = 10,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/coroutine_archer.png",
            gameDescription = "Дальний стрелок, который действует с безопасного расстояния.",
            techDescription = "Коррутины — это асинхронная работа, которая продолжается без блокировки всей системы.",
            strengths = "Длинная дальность и безопасный урон.",
            weaknesses = "Хрупкий, требует прикрытия.",
            realFeature = "Асинхронные задачи эффективны, но требуют планирования и контроля жизненного цикла."
        ),

        UnitType.PATCH_HEALER to UnitConfig(
            unitType = UnitType.PATCH_HEALER,
            displayName = "Patch Healer",
            role = UnitRole.SUPPORT,
            buildTime = 2.4f,
            health = 58,
            speed = 98f,
            damage = 2,
            attackRange = 112f,
            attackCooldownMillis = 1250L,
            costCpu = 4,
            costMemory = 7,
            allocatedMemory = 7,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/patch_healer.png",
            gameDescription = "Восстанавливает живые союзные процессы и помогает удерживать атаку.",
            techDescription = "Патч исправляет поведение живой системы; в отличие от GC, не возвращает мёртвую память.",
            strengths = "Дёшево поддерживает живые юниты.",
            weaknesses = "Хрупкий, не восстанавливает память.",
            realFeature = "Патчирование стабилизирует живые сервисы; это обслуживание, а не сборка мусора."
        ),

        UnitType.STACK_FRAME to UnitConfig(
            unitType = UnitType.STACK_FRAME,
            displayName = "Stack Frame",
            role = UnitRole.ATTACK,
            buildTime = 0.9f,
            health = 38,
            speed = 140f,
            damage = 22,
            attackRange = 54f,
            attackCooldownMillis = 600L,
            costCpu = 3,
            costMemory = 2,
            allocatedMemory = 2,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/stack_frame.png",
            gameDescription = "Краткоживущий атакующий всплеск. Выполняет один быстрый удар, затем возвращается.",
            techDescription = "Stack frame хранит локальные данные для одного вызова функции и исчезает после возврата.",
            strengths = "Дёшево, быстро, хорошо для всплесковых обменов.",
            weaknesses = "Не сохраняется; плохо в долгих боях.",
            realFeature = "Стековое выделение быстро и ограничено временем выполнения функции."
        ),

        UnitType.HEAP_BLOCK to UnitConfig(
            unitType = UnitType.HEAP_BLOCK,
            displayName = "Heap Block",
            role = UnitRole.DEFENSE,
            buildTime = 1.8f,
            health = 115,
            speed = 36f,
            damage = 4,
            attackRange = 45f,
            attackCooldownMillis = 1400L,
            costCpu = 2,
            costMemory = 12,
            allocatedMemory = 12,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/heap_block.png",
            gameDescription = "Массивный блок с большим потреблением Memory. Хорошая стена, плохой темп.",
            techDescription = "Heap-объекты живут дольше одного вызова и должны управляться или собираться.",
            strengths = "Большое HP за счёт CPU; создаёт тело на карте.",
            weaknesses = "Потребляет много Memory и становится утечкой при смерти.",
            realFeature = "Выделение в куче гибкое, но требует управления жизненным циклом."
        ),

        UnitType.POINTER to UnitConfig(
            unitType = UnitType.POINTER,
            displayName = "Pointer",
            role = UnitRole.SUPPORT,
            buildTime = 1.2f,
            health = 44,
            speed = 126f,
            damage = 1,
            attackRange = 150f,
            attackCooldownMillis = 1000L,
            costCpu = 4,
            costMemory = 3,
            allocatedMemory = 3,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/pointer.png",
            gameDescription = "Помечает вражеские цели, чтобы союзные атаки наносили больше урона по отмеченному объекту.",
            techDescription = "Pointer ссылается на объект; сама ссылка лёгкая, но меняет доступ к данным.",
            strengths = "Усиливает сосредоточенный огонь.",
            weaknesses = "Слаб сам по себе и хрупок.",
            realFeature = "Ссылки мощны, потому что многие операции могут указывать на один и тот же объект."
        ),

        UnitType.NULL_POINTER to UnitConfig(
            unitType = UnitType.NULL_POINTER,
            displayName = "Null Pointer",
            role = UnitRole.SPELL,
            buildTime = 0.1f,
            health = 1,
            speed = 0f,
            damage = 34,
            attackRange = 150f,
            attackCooldownMillis = 0L,
            costCpu = 7,
            costMemory = 0,
            allocatedMemory = 0,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/null_pointer.png",
            gameDescription = "Спелл на одного врага, вызывает падение. Наносит урон и кратковременно оглушает ближайший процесс.",
            techDescription = "Доступ к null pointer вызывает крах выполнения, так как код разыменовывает ничего.",
            strengths = "Отличный инструмент для добивания.",
            weaknesses = "Одинокая цель, требует тайминга.",
            realFeature = "Null-ссылки не являются объектами; это недопустимые ссылки."
        ),

        UnitType.EXCEPTION_HANDLER to UnitConfig(
            unitType = UnitType.EXCEPTION_HANDLER,
            displayName = "Exception Handler",
            role = UnitRole.SUPPORT,
            buildTime = 2.0f,
            health = 64,
            speed = 88f,
            damage = 2,
            attackRange = 120f,
            attackCooldownMillis = 1200L,
            costCpu = 5,
            costMemory = 8,
            allocatedMemory = 8,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/exception_handler.png",
            gameDescription = "Защищает nearby союзников от одного фатального краха, перехватывая исключение.",
            techDescription = "Обработка исключений предотвращает локальную ошибку от завершения всего потока.",
            strengths = "Может спасти важный юнит один раз.",
            weaknesses = "Ограниченный щит и слаб в бою.",
            realFeature = "Обработанные исключения сохраняют поток управления; необработанные приводят к краху."
        ),

        UnitType.LOOP to UnitConfig(
            unitType = UnitType.LOOP,
            displayName = "Loop",
            role = UnitRole.ATTACK,
            buildTime = 1.8f,
            health = 72,
            speed = 84f,
            damage = 7,
            attackRange = 72f,
            attackCooldownMillis = 520L,
            costCpu = 5,
            costMemory = 7,
            allocatedMemory = 7,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/loop.png",
            gameDescription = "Многократно повторяет небольшой удар. Эффективен против слабо защищённых целей.",
            techDescription = "Циклы повторяют инструкции, пока не изменится условие.",
            strengths = "Постоянное повторяющееся давление.",
            weaknesses = "Низкий взрывной урон и уязвимость к контролю области.",
            realFeature = "Циклы просты и мощны, но плохие условия завершения создают неконтролируемую работу."
        ),

        UnitType.RECURSIVE_CALL to UnitConfig(
            unitType = UnitType.RECURSIVE_CALL,
            displayName = "Recursive Call",
            role = UnitRole.ATTACK,
            buildTime = 2.5f,
            health = 68,
            speed = 78f,
            damage = 12,
            attackRange = 82f,
            attackCooldownMillis = 900L,
            costCpu = 6,
            costMemory = 9,
            allocatedMemory = 9,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/recursive_call.png",
            gameDescription = "Становится сильнее каждые несколько секунд, но в конечном счёте рискует повредить себя из-за переполнения стека.",
            techDescription = "Рекурсия элегантно решает вложенные задачи, но каждый вызов потребляет глубину стека.",
            strengths = "Усиливается при наличии защиты.",
            weaknesses = "Может причинить себе урон при слишком большой глубине.",
            realFeature = "Рекурсивные алгоритмы нуждаются в базовом случае и контроле глубины."
        ),

        UnitType.MUTEX to UnitConfig(
            unitType = UnitType.MUTEX,
            displayName = "Mutex",
            role = UnitRole.DEFENSE,
            buildTime = 2.6f,
            health = 118,
            speed = 54f,
            damage = 8,
            attackRange = 72f,
            attackCooldownMillis = 980L,
            costCpu = 6,
            costMemory = 9,
            allocatedMemory = 9,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/mutex.png",
            gameDescription = "Защищает nearby союзные процессы, уменьшая входящий урон.",
            techDescription = "Mutex позволяет одному потоку одновременно входить в критическую секцию.",
            strengths = "Аура смягчения урона.",
            weaknesses = "Медленный и может способствовать риску взаимной блокировки при неправильном использовании.",
            realFeature = "Взаимное исключение повышает корректность, но может уменьшить параллелизм."
        ),

        UnitType.SEMAPHORE to UnitConfig(
            unitType = UnitType.SEMAPHORE,
            displayName = "Semaphore",
            role = UnitRole.SUPPORT,
            buildTime = 2.4f,
            health = 76,
            speed = 76f,
            damage = 3,
            attackRange = 90f,
            attackCooldownMillis = 1100L,
            costCpu = 6,
            costMemory = 8,
            allocatedMemory = 8,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/semaphore.png",
            gameDescription = "Увеличивает пропускную способность nearby союзных процессов, позволяя ограниченный параллельный доступ.",
            techDescription = "Semaphore контролирует, сколько работников могут использовать ресурс одновременно.",
            strengths = "Локальная аура скорости/темпа атаки.",
            weaknesses = "Слаб в одиночку, нужен отряд.",
            realFeature = "Семафоры координируют ограниченный параллелизм, а не эксклюзивный доступ."
        ),

        UnitType.OBSERVER to UnitConfig(
            unitType = UnitType.OBSERVER,
            displayName = "Observer",
            role = UnitRole.SUPPORT,
            buildTime = 1.7f,
            health = 48,
            speed = 112f,
            damage = 1,
            attackRange = 170f,
            attackCooldownMillis = 1400L,
            costCpu = 4,
            costMemory = 5,
            allocatedMemory = 5,
            memoryWorkPower = 0f,
            cpuRedirectPower = 0f,
            sprite = "units/observer.png",
            gameDescription = "Помечает врагов с дистанции, делая их уязвимее.",
            techDescription = "Паттерн Наблюдатель позволяет объектам реагировать на изменения без жёсткой связки.",
            strengths = "Улучшает фокус команды и видимость целей.",
            weaknesses = "Хрупкий и наносит мало прямого урона.",
            realFeature = "Наблюдатели разъединяют уведомление и действие, но неконтролируемые слушатели могут приводить к утечкам памяти."
        )
    )

    val defaultDeck: List<UnitType> = listOf(
        UnitType.ALLOCATOR,
        UnitType.BUFFER,
        UnitType.CPU_SCHEDULER,
        UnitType.CACHE_RUNNER,
        UnitType.GARBAGE_COLLECTOR,
        UnitType.THREAD_GUARD,
        UnitType.INJECTOR,
        UnitType.PATCH_HEALER,
        UnitType.DEADLOCK,
        UnitType.OVERCLOCK
    )

    fun getConfig(type: UnitType): UnitConfig {
        return units[type] ?: error("No UnitConfig registered for $type")
    }

    fun all(): List<UnitConfig> {
        return units.values.toList()
    }
}
